/*
** Beaver's an Early AdVanced EditoR
** (C) 1999-2000 Marc Bevand, Damien Terrier and Emmanuel Turquin
**
** wordfile.h
**
** Author<s>:   Marc Bevand (aka "After") <bevand_m@epita.fr>
** Last update: Mon Feb 25 21:43:19 CET 2002
** Description: This header define a big gchar * representing a
**              standard UltraEdit's "wordfile.txt"
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

gchar			*default_wordfile = 
"/L1\"C/C++\" Line Comment = // Block Comment On = /* Block Comment Off = */ Escape Char = \\ String Chars = \"' File Extensions = C CC CPP CXX H HH HPP\n"
"/Delimiters = ~!@%^&*()-+=|\\{}[]<>:;\"' ,	.?\n"
"/Function String = \"%[a-zA-Z_]*)[~;]\"\n"
"/Indent Strings = \"{\"\n"
"/Unindent Strings = \"}\"\n"
"\n"
"/C1\"Blue Keywords\"\n"
"bool\n"
"char class const case catch const_cast\n"
"double default do delete dynamic_cast\n"
"else enum explicit export\n"
"for false float friend\n"
"if inline int\n"
"long\n"
"mutable\n"
"new namespace\n"
"operator\n"
"protected private public\n"
"reinterpret_cast return\n"
"short signed sizeof struct static_cast switch\n"
"template throw true typedef typename this try typeid\n"
"union unsigned using\n"
"virtual void volatile\n"
"wchar_t while\n"
"\n"
"/C2\"Red Keywords\"\n"
"asm auto\n"
"break\n"
"continue\n"
"extern\n"
"goto\n"
"register \n"
"static\n"
"\n"
"/C3\"Hash directives\"\n"
"#define #error #include #elif #if #line #else #ifdef #pragma #endif #ifndef #undef\n"
"\n"
"/C4\"Operators\"\n"
"+\n"
"-\n"
"=\n"
"// /\n"
"%\n"
"&\n"
">\n"
"<\n"
"^\n"
"!\n"
"|\n"
"*\n"
"^\n"
"\n"
"/C5\"Punctuators\"\n"
"{\n"
"}\n"
";\n"
"(\n"
")\n"
",\n"
"\n"
"/L2\"HTML\" Nocase Noquote HTML_LANG Block Comment On = <!-- Block Comment Off = --> Block Comment On Alt = <% Block Comment Off Alt = %> String Chars = \"' File Extensions = HTM HTML ASP SHTM SHTML HTT JSP\n"
"/Delimiters = ~@$%^&*()+=|\\{}[]:;\"'<> ,	.?\n"
"/Function String = \"name=*\">\"\n"
"/C1 TAGS\n"
"<A </A> <ABBR> <ABBR </ABBR> <ABOVE> <ACRONYM> <ACRONYM </ACRONYM> <ADDRESS> <ADDRESS </ADDRESS> <APPLET </APPLET> <AREA <ARRAY>\n"
"<B> <B </B> <BASE <BASEFONT <BDO> <BDO </BDO> <BGSOUND <BIG> <BIG </BIG> <BLINK> <BLINK </BLINK> <BLOCKQUOTE> <BLOCKQUOTE </BLOCKQUOTE> <BODY <BODY> </BODY> <BOX> <BR <BR> <BUTTON> </BUTTON>\n"
"<CAPTION> <CAPTION </CAPTION> <CENTER> <CENTER </CENTER> <CITE> <CITE </CITE> <CODE> <CODE </CODE> <COL> <COLGROUP> </COLGROUP> <COMMENT> </COMMENT> \n"
"<DD> <DD </DD> <DEL> <DEL </DEL> <DFN> <DFN </DFN> <DIR> <DIR </DIR> <DIV> <DIV </DIV> <DL> <DL </DL> <DT> <DT  </DT> \n"
"<EM> <EM </EM> <EMBED\n"
"<FIELDSET> <FIELDSET </FIELDSET> <FIG> <FONT </FONT> <FORM> <FORM </FORM> <FRAME <FRAMESET </FRAMESET>\n"
"<H1> <H1 </H1> <H2> <H2 </H2> <H3> <H3 </H3> <H4> <H4 </H4> <H5> <H5 </H5> <H6> <H6 </H6> <HEAD> <HEAD </HEAD> <HR> <HR <HTML> <HTML </HTML>\n"
"<I> <I </I> <IFRAME> </IFRAME> <ILAYER> </ILAYER> <IMG <INPUT> <INPUT <INS> <INS </INS> <ISINDEX> <ISINDEX \n"
"<KBD> <KBD </KBD>\n"
"<LABEL> <LABEL </LABEL> <LAYER> <LEGEND> <LEGEND </LEGEND> <LI> <LI </LI> <LINK <LISTING> </LISTING>\n"
"<MAP </MAP> <MARQUEE </MARQUEE> <MENU> <MENU </MENU> <META <MULTICOL> </MULTICOL>\n"
"<NEXTID <NOFRAMES> </NOFRAMES> <NOLAYER> </NOLAYER> <NOSCRIPT> </NOSCRIPT> <NOTE> </NOTE> \n"
"<OBJECT> <OBJECT <OL> <OL </OL> <OPTGROUP> <OPTGROUP </OPTGROUP> <OPTION> <OPTION \n"
"<P <P> </P> <PARAM <PRE> <PRE </PRE>\n"
"<Q> <Q </Q> <QUOTE>\n"
"<RANGE> <ROOT>\n"
"<S> <S </S> <SAMP> <SAMP </SAMP> <SCRIPT <SCRIPT> </SCRIPT> <SELECT </SELECT> <SMALL> <SMALL </SMALL> <SOUND <SPACER> <SPAN> <SPAN </SPAN> <SQRT> <STRIKE> <STRIKE </STRIKE> <STRONG> <STRONG </STRONG> <STYLE> <STYLE </STYLE> <SUB> <SUB </SUB> <SUP> <SUP </SUP>\n"
"<TABLE> <TABLE </TABLE> <TBODY> <TBODY </TBODY> <TD <TD> </TD> <TEXT> <TEXTAREA <TEXTAREA> </TEXTAREA> <TFOOT> <TFOOT </TFOOT> <TH <TH> </TH> <THEAD> <THEAD </THEAD> <TITLE> </TITLE> <TR <TR> </TR> <TT> </TT> <TT\n"
"<U> <U </U> <UL> <UL </UL> \n"
"<VAR> </VAR> <VAR\n"
"<WBR>\n"
"<XMP> </XMP>\n"
"/C2 ATTRIBUTES\n"
"ABBR= ACCEPT-CHARSET= ACCEPT= ACCESSKEY= ACTION= ALIGN= ALINK= ALT= ARCHIVE= AXIS=\n"
"BACKGROUND= BEHAVIOR BELOW BGCOLOR= BORDER=\n"
"CELLPADDING= CELLSPACING= CHAR= CHAROFF= CHARSET= CHECKED CITE= CLASS= CLASSID= CLEAR= CODE= CODEBASE= CODETYPE= COLOR= COLS= COLSPAN= COMPACT CONTENT= COORDS=\n"
"DATA= DATETIME= DECLARE DEFER DIR= DISABLED\n"
"ENCTYPE=\n"
"FACE= FOR= FRAME= FRAMEBORDER= FRAMESPACING=\n"
"HEADERS= HEIGHT= HIDDEN= HREF= HREFLANG= HSPACE= HTTP-EQUIV=\n"
"ID= ISMAP=\n"
"LABEL= LANG= LANGUAGE= LINK= LOOP= LONGDESC=\n"
"MAILTO= MARGINHEIGHT= MARGINWIDTH= MAXLENGTH= MEDIA= METHOD= MULTIPLE\n"
"NAME= NOHREF NORESIZE NOSHADE\n"
"OBJECT= ONBLUR= ONCHANGE= ONFOCUS= ONKEYDOWN= ONKEYPRESS= ONKEYUP= ONLOAD= ONRESET= ONSELECT= ONSUBMIT= ONUNLOAD= ONCLICK= ONDBLCLICK= ONMOUSEDOWN= ONMOUSEMOVE= ONMOUSEOUT= ONMOUSEOVER= ONMOUSEUP=\n"
"PROFILE= PROMPT=\n"
"READONLY REL= REV= ROWS= ROWSPAN= RULES=\n"
"SCHEME= SCOPE= SCROLLING= SELECTED SHAPE= SIZE= SPAN= SRC= STANDBY= START= STYLE= SUMMARY=\n"
"TABINDEX= TARGET= TEXT= TITLE= TOPMARGIN= TYPE=\n"
"URL= USEMAP=\n"
"VALIGN= VALUE= VALUETYPE= VERSION= VLINK= VSPACE=\n"
"WIDTH=\n"
"=\n"
"\n"
"/L3\"Perl\" 1Line Comment = # File Extensions = CGI PL PM\n"
"/Delimiters = ~!@$%^&*()+=|\\/{}[]:;\"'<> 	,.?/	\n"
"/Marker Characters = \"$@\" \n"
"/Indent Strings = \"{\"\n"
"/Unindent Strings = \"}\"\n"
"/C1 \n"
"-A -B -C -M -O -R -S -T -W -X -b -c -d -e -f -g -k -l -o -p -r -s -t -u -w -x -z     \n"
"__DATA__ __END__ __FILE__ __LINE__\n"
"continue  \n"
"do        \n"
"else elsif     \n"
"for foreach  \n"
"goto               \n"
"if                 \n"
"last local     \n"
"my        \n"
"next no        \n"
"package   \n"
"redo return require   \n"
"sub         \n"
"until unless use      \n"
"while    \n"
"/C2\n"
"accept alarm atan2\n"
"bind binmode bless\n"
"caller chdir chmod chomp chop chown chr chroot close closedir connect cos crypt\n"
"dbmclose dbmopen defined delete die dump\n"
"each endgrent endhostent endnetent endprotoent endpwent endservent eof eval exec exit exp exists\n"
"fcntl fileno flock fork formline format \n"
"getc getgrent getgrgid getgrname gethostbyaddr gethostbyname gethostent getlogin getnetbyaddr getnetbyname getnetent getpeername getpgrp getppid getpriority getprotobyname getprotobynumber getprotoent getpwent getpwnam getpwuid getservbyname getservbyport getservent getsockname getsockopt glob gmtime grep\n"
"hex\n"
"index int ioctl\n"
"join \n"
"keys kill\n"
"lc lcfirst length link listen localtime log lstat \n"
"map mkdir msgctl msgget msgrcv msgsnd\n"
"oct open opendir ord \n"
"pack pipe pop pos print printf push \n"
"quotemeta\n"
"rand read readdir readline readlink recv ref rename reset reverse rewinddir rindex rmdir \n"
"scalar seek seekdir select semctl semgett semop send setgrent sethostent setnetent setpgrp setpriority setprotoent setpwent setservent setsockopt shift shmctl shmget shmread shmwrite shutdown sin sleep socket socketpair sort splice split sprintf sqrt srand stat study substr symlink syscall sysopen sysread system syswrite\n"
"tell telldir tie tied time times truncate \n"
"uc ucfirst umask undef unlink unpack unshift utime untie\n"
"values vec \n"
"wait waitpid wantarray warn write \n"
"/C3\n"
"AUTOLOAD \n"
"and\n"
"BEGIN\n"
"CORE \n"
"cmp\n"
"DESTROY\n"
"eq \n"
"END \n"
"ge gt \n"
"le lt \n"
"ne not \n"
"m \n"
"or\n"
"q qq qw qx \n"
"SUPER \n"
"s \n"
"tr\n"
"UNIVERSAL\n"
"x xor\n"
"y\n"
"/C4\n"
"$@\n"
"@\n"
"\n"
"/L4\"JavaScript\" Line Comment = // Block Comment On = /* Block Comment Off = */ File Extensions = JS\n"
"/Delimiters = ~!@%^&*()-+=|\\/{}[]:;\"'<> ,	.?\n"
"/Function String = \"%[ 	]+[psv]*(*)*{\"\n"
"/Indent Strings = \"{\"\n"
"/Unindent Strings = \"}\"\n"
"/C1 \"Keywords\"\n"
"abstract\n"
"byte\n"
"case catch char class const continue\n"
"default delete do double\n"
"else extends\n"
"false final finally float for function\n"
"goto\n"
"if implements import in instanceof int interface\n"
"long\n"
"native new null\n"
"package private protected public\n"
"reset return\n"
"short static super switch synchronized\n"
"this throw transient true try\n"
"var void\n"
"while with\n"
"/C2\"Methods\"\n"
"$n\n"
"above abs acos action activeElement alert alinkColor all altKey anchor anchors appCodeName applets apply appName appVersion arguments arity asin assign atan atan2 atob availHeight availLeft availTop availWidth\n"
"back background below bgColor big blink blur bold border borderWidths bottom btoa button\n"
"call callee caller cancelBubble captureEvents ceil charAt charCodeAt charset checked children classes className clear clearInterval clearTimeout click clientInformation clientX clientY close closed colorDepth compile complete concat confirm constructir contains contextual cookie cos crypto ctrlKey current\n"
"data defaultCharset defaultChecked defaultSelected defaultStatus defaultValue description disableExternalCapture disablePrivilege document domain\n"
"E element FromPoint elements embeds enabledPlugin enableExternalCapture enablePrivilege encoding escape eval event exec exp expando\n"
"fgColor fileName find fixed floor focus fontColor fontSize form forms forward frames fromCharCode fromElement\n"
"getAttribute get getClass getDate getDay getFullYear getHours getMember getMilliseconds getMinutes getMonth getSeconds getSelection getSlot getTime getTimezoneOffset getUTCDate getUTCDay getUTCFullYear getUTCHours getUTCMilliseconds getUTCMinutes getUTCMonth getUTCSeconds getWindow getYear global go\n"
"HandleEvent hash hidden history home host hostName href hspace\n"
"id ids ignoreCase images index indexOf inner Height innerHTML innerText innerWidth insertAdjacentHTML insertAdjacentText isFinite isNAN italics\n"
"java javaEnabled join\n"
"keyCode\n"
"lang language lastIndex lastIndexOf lastMatch lastModified lastParen layers layerX layerY left leftContext length link linkColor Links LN10 LN2 load location locationBar log LOG10E LOG2E lowsrc\n"
"margins match max MAX_VALUE menubar method mimeTypes min MIN_VALUE modifiers moveAbove moveBelow moveBy moveTo moveToAbsolute multiline\n"
"name NaN navigate navigator NEGATIVE_INFINITY netscape next\n"
"offscreenBuffering offset offsetHeight offsetLeft offsetParent offsetTop offsetWidth offsetX offsetY onabort onblur onchange onclick ondblclick ondragdrop onerror onfocus onHelp onkeydown onkeypress onkeyup onload onmousedown onmousemove onmouseout onmouseover onmouseup onmove onreset onresize onsubmit onunload open opener options outerHeight outerHTML outerText outerWidth\n"
"paddings pageX pageXOffset pageY pageYOffset parent parentElement parentLayer parentWindow parse parseFloat parseInt pathname personalbar PI pixelDepth platform plugins pop port POSITIVE_INFINITY pow preference previous print prompt protocol prototype push\n"
"random readyState reason referrer refresh releaseEvents reload removeAttribute removeMember replace reset resizeBy resizeTo returnValue reverse right rightcontext\n"
"screenX screenY scroll scrollbars scrollBy scrollIntoView scrollTo search select selected selectedIndex self setAttribute setDay setFullYear setHotkeys setHours setInterval setMember setMilliseconds setMinutes setMonth setResizable setSeconds setSlot setTime setTimeout setUTCDate setUTCFullYear setUTCHours setUTCMillseconds setUTCMinutes setUTCMonth setUTCSeconds setYear setZOptions shift shiftKey siblingAbove siblingBelow signText sin slice smallsort source sourceIndex splice split sqrt SQRT1_2 SQRT2 src srcElement srcFilter status statusbar stop strike style sub submit substr substring suffixes sun sup systemLanguage\n"
"tagName tags taint taintEnabled tan target test text title toElement toGMTString toLocaleString toLowerCase toolbar top toString toUpperCase toUTCString TYPE type typeOf\n"
"unescape unshift untaint unwatch userAgent userLanguage UTC\n"
"value valueOf visibility vlinkColor vspace\n"
"watch which width window write writeln\n"
"x\n"
"y\n"
"zIndex\n"
"/C3\"Objects\"\n"
"Anchor Applet Area Arguments Array\n"
"Boolean Button\n"
"Checkbox Crypto\n"
"Date Document\n"
"Element Event\n"
"FileUpload Form Frame Function\n"
"Hidden History HTMLElement\n"
"Image Infinity Input\n"
"JavaArray JavaClass JavaObject JavaPackage JSObject\n"
"Layer Link\n"
"Math MimeType\n"
"Navigator Number\n"
"Object Option\n"
"Packages Password Plugin PrivilegeManager\n"
"Random RegExp\n"
"Screen Select String Submit\n"
"Text Textarea\n"
"URL\n"
"Window\n"
"\n"
"/L5\"PHP\" Nocase  HTML_LANG 1Line Comment = // Block Comment On = /* Block Comment Off = */ File Extensions = PHP PHTML PHP3 PHP4 PHPS\n"
"/Delimiters = ~!@$%^&*()-+=|\\{}[]:;\"'<> ,	.?\n"
"/C1\n"
"break\n"
"case\n"
"default\n"
"echo else elseif end endif endwhile endswitch exit\n"
"for\n"
"global\n"
"if include\n"
"switch\n"
"while\n"
"/C2\n"
"abs acos ada_afetch ada_autocommit ada_close ada_commit ada_connect ada_exec ada_fetchrow ada_fieldname ada_fieldnum ada_fieldtype ada_freeresult \n"
"ada_numfields ada_numrows ada_result ada_resultall ada_rollback addslashes apache_lookup_uri apache_note array array_keys array_merge array_pop \n"
"array_push array_shift array_slice array_splice array_unshift array_values array_walk arsort asin asort aspell_check aspell_check_raw aspell_new \n"
"aspell_suggest atan atan2\n"
"base64_decode base64_encode base_convert basename bcadd bccomp bcdiv bcmod bcmul bcpow bcscale bcsqrt bcsub bin2hex bindec\n"
"ceil chdir checkdate checkdnsrr chgrp chmod chop chown chr chunk_split clearstatcache closedir closelog compact connection_aborted connection_status \n"
"connection_timeout convert_cyr_string copy cos count cpdf_add_annotation cpdf_add_outline cpdf_arc cpdf_begin_text cpdf_circle cpdf_clip cpdf_close \n"
"cpdf_closepath cpdf_closepath_fill_stroke cpdf_closepath_stroke cpdf_continue_text cpdf_curveto cpdf_end_text cpdf_endpath cpdf_fill cpdf_fill_stroke \n"
"cpdf_finalize cpdf_finalize_page cpdf_import_jpeg cpdf_lineto cpdf_moveto cpdf_open cpdf_output_buffer cpdf_page_init cpdf_place_inline_image cpdf_rect \n"
"cpdf_restore cpdf_rlineto cpdf_rmoveto cpdf_rotate cpdf_save cpdf_save_to_file cpdf_scale cpdf_set_char_spacing cpdf_set_creator cpdf_set_current_page \n"
"cpdf_set_font cpdf_set_horiz_scaling cpdf_set_keywords cpdf_set_leading cpdf_set_page_animation cpdf_set_subject cpdf_set_text_matrix cpdf_set_text_pos \n"
"cpdf_set_text_rendering cpdf_set_text_rise cpdf_set_title cpdf_set_word_spacing cpdf_setdash cpdf_setflat cpdf_setgray cpdf_setgray_fill \n"
"cpdf_setgray_stroke cpdf_setlinecap cpdf_setlinejoin cpdf_setlinewidth cpdf_setmiterlimit cpdf_setrgbcolor cpdf_setrgbcolor_fill cpdf_setrgbcolor_stroke \n"
"cpdf_show cpdf_show_xy cpdf_stringwidth cpdf_stroke cpdf_text cpdf_translate crypt current\n"
"date dba_close dba_delete dba_exists dba_fetch dba_firstkey dba_insert dba_nextkey dba_open dba_optimize dba_popen dba_replace dba_sync dbase_add_record \n"
"dbase_close dbase_create dbase_delete_record dbase_get_record dbase_get_record_with_names dbase_numfields dbase_numrecords dbase_open dbase_pack \n"
"dbase_replace_record dblist dbmclose dbmdelete dbmexists dbmfetch dbmfirstkey dbminsert dbmnextkey dbmopen dbmreplace debugger_off debugger_on decbin \n"
"dechex decoct delete die dir dirname diskfreespace dl doubleval\n"
"each easter_date easter_days empty ereg ereg_replace eregi eregi_replace error_log error_reporting escapeshellcmd eval exec exp explode extension_loaded extract\n"
"fclose fdf_close fdf_create fdf_get_file fdf_get_status fdf_get_value fdf_next_field_name fdf_open fdf_save fdf_set_ap fdf_set_file fdf_set_status fdf_set_value feof fgetc\n"
"fgetcsv fgets fgetss file file_exists fileatime filectime filegroup fileinode filemtime fileowner fileperms filepro filepro_fieldcount filepro_fieldname filepro_fieldtype\n"
"filepro_fieldwidth filepro_retrieve filepro_rowcount filesize filetype flock floor flush fopen fpassthru fputs fread frenchtojd fseek fsockopen ftell function_exists fwrite\n"
"get_cfg_var get_current_user get_magic_quotes_gpc get_magic_quotes_runtime get_meta_tags getallheaders getdate getenv gethostbyaddr gethostbyname gethostbynamel getimagesize\n"
"getlastmod getmxrr getmyinode getmypid getmyuid getrandmax getrusage gettimeofday gettype gmdate gmmktime gmstrftime gregoriantojd gzclose gzeof gzfile gzgetc gzgets gzgetss\n"
"gzopen gzpassthru gzputs gzread gzrewind gzseek gztell gzwrite\n"
"header hexdec htmlentities htmlspecialchars hw_children hw_childrenobj hw_close hw_connect hw_cp hw_deleteobject hw_docbyanchor hw_docbyanchorobj hw_documentattributes\n"
"hw_documentbodytag hw_documentcontent hw_documentsetcontent hw_documentsize hw_edittext hw_error hw_errormsg hw_free_document hw_getanchors hw_getanchorsobj hw_getandlock\n"
"hw_getchildcoll hw_getchildcollobj hw_getchilddoccoll hw_getchilddoccollobj hw_getobject hw_getobjectbyquery hw_getobjectbyquerycoll hw_getobjectbyquerycollobj\n"
"hw_getobjectbyqueryobj hw_getparents hw_getparentsobj hw_getremote hw_getremotechildren hw_getsrcbydestobj hw_gettext hw_getusername hw_identify hw_incollections hw_info\n"
"hw_inscoll hw_insdoc hw_insertdocument hw_insertobject hw_modifyobject hw_mv hw_new_document hw_objrec2array hw_outputdocument hw_pconnect hw_pipedocument hw_root hw_unlock\n"
"hw_who\n"
"ibase_bind ibase_close ibase_connect ibase_execute ibase_fetch_row ibase_free_query ibase_free_result ibase_pconnect ibase_prepare ibase_query ibase_timefmt icap_close\n"
"icap_delete_event icap_fetch_event icap_list_alarms icap_t_events icap_open icap_snooze icap_store_event ifx_affected_rows ifx_blobinfile_mode ifx_byteasvarchar ifx_close\n"
"ifx_connect ifx_copy_blob ifx_create_blob ifx_create_char ifx_do ifx_error ifx_errormsg ifx_fetch_row ifx_fieldproperties ifx_fieldtypes ifx_free_blob ifx_free_char\n"
"ifx_free_result ifx_get_blob ifx_get_char ifx_getsqlca ifx_htmltbl_result ifx_nullformat ifx_num_fields ifx_num_rows ifx_pconnect ifx_prepare ifx_query ifx_textasvarchar\n"
"ifx_update_blob ifx_update_char ifxus_close_slob ifxus_create_slob ifxus_free_slob ifxus_open_slob ifxus_read_slob ifxus_seek_slob ifxus_tell_slob ifxus_write_slob\n"
"ignore_user_abort imagearc imagechar imagecharup imagecolorallocate imagecolorat imagecolorclosest imagecolorexact imagecolorresolve imagecolorset imagecolorsforindex\n"
"imagecolorstotal imagecolortransparent imagecopyresized imagecreate imagecreatefromgif imagedashedline imagedestroy imagefill imagefilledpolygon imagefilledrectangle\n"
"imagefilltoborder imagefontheight imagefontwidth imagegif imageinterlace imageline imageloadfont imagepolygon imagepsbbox imagepsencodefont imagepsfreefont imagepsloadfont\n"
"imagepstext imagerectangle imagesetpixel imagestring imagestringup imagesx imagesy imagettfbbox imagettftext imap_8bit imap_alerts imap_append imap_base64 imap_binary\n"
"imap_body imap_check imap_clearflag_full imap_close imap_createmailbox imap_delete imap_deletemailbox imap_errors imap_expunge imap_fetchbody imap_fetchheader\n"
"imap_fetchstructure imap_getmailboxes imap_getsubscribed imap_header imap_headers imap_last_error imap_listmailbox imap_listsubscribed imap_mail_copy imap_mail_move\n"
"imap_mailboxmsginfo imap_msgno imap_num_msg imap_num_recent imap_open imap_ping imap_qprint imap_renamemailbox imap_reopen imap_rfc822_parse_adrlist imap_rfc822_write_address\n"
"imap_scanmailbox imap_search imap_setflag_full imap_sort imap_status imap_subscribe imap_uid imap_undelete imap_unsubscribe implode in_array intval iptcparse is_array\n"
"is_dir is_double is_executable is_file is_float is_int is_integer is_link is_long is_object is_readable is_real is_string is_writeable isset\n"
"jddayofweek jdmonthname  jdtofrench jdtogregorian jdtojewish jdtojulian jewishtojd join juliantojd\n"
"key ksort\n"
"ldap_add ldap_bind ldap_close ldap_connect ldap_count_entries ldap_delete ldap_dn2ufn ldap_explode_dn ldap_first_attribute ldap_first_entry ldap_free_result\n"
"ldap_get_attributes ldap_get_dn ldap_get_entries ldap_get_values ldap_list ldap_mod_add ldap_mod_del ldap_mod_replace ldap_modify ldap_next_attribute ldap_next_entry\n"
"ldap_read ldap_search ldap_unbind leak link linkinfo list log log10 lstat ltrim\n"
"mail max mcrypt_cbc mcrypt_cfb mcrypt_create_iv mcrypt_ecb mcrypt_get_block_size mcrypt_get_cipher_name mcrypt_get_key_size mcrypt_ofb md5 mhash mhash_count\n"
"mhash_get_block_size mhash_get_hash_name microtime min mkdir mktime msql msql_affected_rows msql_close msql_connect msql_create_db msql_createdb msql_data_seek\n"
"msql_dbname msql_drop_db msql_dropdb msql_error msql_fetch_array msql_fetch_field msql_fetch_object msql_fetch_row msql_field_seek msql_fieldflags msql_fieldlen\n"
"msql_fieldname msql_fieldtable msql_fieldtype msql_free_result msql_freeresult msql_list_dbs msql_list_fields msql_list_tables msql_listdbs msql_listfields msql_listtables\n"
"msql_num_fields msql_num_rows msql_numfields msql_numrows msql_pconnect msql_query msql_regcase msql_result msql_select_db msql_selectdb msql_tablename mssql_affected_rows\n"
"mssql_close mssql_connect mssql_data_seek mssql_fetch_array mssql_fetch_field mssql_fetch_object mssql_fetch_row mssql_field_seek mssql_free_result mssql_num_fields\n"
"mssql_num_rows mssql_pconnect mssql_query mssql_result mssql_select_db mt_getrandmax mt_rand mt_srand mysql_affected_rows mysql_close mysql_connect mysql_create_db\n"
"mysql_data_seek mysql_db_query mysql_drop_db mysql_errno mysql_error mysql_fetch_array mysql_fetch_field mysql_fetch_lengths mysql_fetch_object mysql_fetch_row\n"
"mysql_field_flags mysql_field_len mysql_field_name mysql_field_seek mysql_field_table mysql_field_type mysql_free_result mysql_insert_id mysql_list_dbs mysql_list_fields\n"
"mysql_list_tables mysql_num_fields mysql_num_rows mysql_pconnect mysql_query mysql_result mysql_select_db mysql_tablename\n"
"next nl2br number_format\n"
"ocibindbyname ocicolumnisnull ocicolumnname ocicolumnsize ocicolumntype ocicommit ocidefinebyname ocierror ociexecute ocifetch ocifetchinto ocifetchstatement ocifreecursor\n"
"ocifreestatement ociinternaldebug ocilogoff ocilogon ocinewcursor ocinewdescriptor ocinlogon ocinumcols ocinumrows ociparse ociplogon ociresult ocirollback ocirowcount\n"
"ociserverversion ocistatementtype octdec odbc_autocommit odbc_binmode odbc_close odbc_close_all odbc_commit odbc_connect odbc_cursor odbc_do odbc_exec odbc_execute\n"
"odbc_fetch_into odbc_fetch_row odbc_field_len odbc_field_name odbc_field_type odbc_free_result odbc_longreadlen odbc_num_fields odbc_num_rows odbc_pconnect odbc_prepare\n"
"odbc_result odbc_result_all odbc_rollback odbc_setoption opendir openlog ora_bind ora_close ora_columnname ora_columntype ora_commit ora_commitoff ora_commiton ora_error\n"
"ora_errorcode ora_exec ora_fetch ora_getcolumn ora_logoff ora_logon ora_open ora_parse ora_rollback ord\n"
"pack parse_str parse_url passthru pclose pdf_add_annotation pdf_add_outline pdf_arc pdf_begin_page pdf_circle pdf_clip pdf_close pdf_close_image pdf_closepath\n"
"pdf_closepath_fill_stroke pdf_closepath_stroke pdf_continue_text pdf_curveto pdf_end_page pdf_endpath pdf_execute_image pdf_fill pdf_fill_stroke pdf_get_info pdf_lineto\n"
"pdf_moveto pdf_open pdf_open_gif pdf_open_jpeg pdf_open_memory_image pdf_place_image pdf_put_image pdf_rect pdf_restore pdf_rotate pdf_save pdf_scale pdf_set_char_spacing\n"
"pdf_set_duration pdf_set_font pdf_set_horiz_scaling pdf_set_info_author pdf_set_info_creator pdf_set_info_keywords pdf_set_info_subject pdf_set_info_title pdf_set_leading\n"
"pdf_set_text_matrix pdf_set_text_pos pdf_set_text_rendering pdf_set_text_rise pdf_set_transition pdf_set_word_spacing pdf_setdash pdf_setflat pdf_setgray pdf_setgray_fill\n"
"pdf_setgray_stroke pdf_setlinecap pdf_setlinejoin pdf_setlinewidth pdf_setmiterlimit pdf_setrgbcolor pdf_setrgbcolor_fill pdf_setrgbcolor_stroke pdf_show pdf_show_xy\n"
"pdf_stringwidth pdf_stroke pdf_translate pfsockopen pg_close pg_cmdtuples pg_connect pg_dbname pg_errormessage pg_exec pg_fetch_array pg_fetch_object pg_fetch_row\n"
"pg_fieldisnull pg_fieldname pg_fieldnum pg_fieldprtlen pg_fieldsize pg_fieldtype pg_freeresult pg_getlastoid pg_host pg_loclose pg_locreate pg_loopen pg_loread pg_loreadall\n"
"pg_lounlink pg_lowrite pg_numfields pg_numrows pg_options pg_pconnect pg_port pg_result pg_tty phpinfo phpversion pi popen pos pow preg_grep preg_match preg_match_all\n"
"preg_quote preg_replace preg_split prev print printf putenv\n"
"quoted_printable_decode quotemeta\n"
"rand range rawurldecode rawurlencode readdir readfile readgzfile readlink register_shutdown_function rename require reset return rewind rewinddir rmdir round rsort\n"
"sem_acquire sem_get sem_release serialize session_decode session_destroy session_encode session_id session_is_registered session_module_name session_name session_register\n"
"session_save_path session_start session_unregister set_file_buffer set_magic_quotes_runtime set_socket_blocking set_time_limit setcookie setlocale settype shm_attach\n"
"shm_detach shm_get_var shm_put_var shm_remove shm_remove_var shuffle similar_text sin sizeof sleep snmp_get_quick_print snmp_set_quick_print snmpget snmpset snmpwalk\n"
"snmpwalkoid solid_close solid_connect solid_exec solid_fetchrow solid_fieldname solid_fieldnum solid_freeresult solid_numfields solid_numrows solid_result sort soundex split\n"
"sprintf sql_regcase sqrt srand stat str_replace strchr strcmp strcspn strftime strip_tags stripslashes strlen strpos strrchr strrev strrpos strspn strstr strtok strtolower\n"
"strtoupper strtr strval substr sybase_affected_rows sybase_close sybase_connect sybase_data_seek sybase_fetch_array sybase_fetch_field sybase_fetch_object sybase_fetch_row\n"
"sybase_field_seek sybase_free_result sybase_num_fields sybase_num_rows sybase_pconnect sybase_query sybase_result sybase_select_db symlink syslog system\n"
"tan tempnam time touch trim\n"
"uasort ucfirst ucwords uksort umask uniqid unlink unpack unserialize unset urldecode urlencode usleep usort utf8_decode utf8_encode\n"
"virtual vm_addalias vm_adduser vm_delalias vm_deluser vm_passwd\n"
"wddx_add_vars wddx_deserialize wddx_packet_end wddx_packet_start wddx_serialize_value wddx_serialize_vars\n"
"xml_error_string xml_get_current_byte_index xml_get_current_column_number xml_get_current_line_number xml_get_error_code xml_parse xml_parser_create xml_parser_free\n"
"xml_parser_get_option xml_parser_set_option xml_set_character_data_handler xml_set_default_handler xml_set_element_handler xml_set_external_entity_ref_handler\n"
"xml_set_notation_decl_handler xml_set_processing_instruction_handler xml_set_unparsed_entity_decl_handler\n"
"yp_err_string yp_errno yp_first yp_get_default_domain yp_master yp_match yp_next yp_order\n"
"\n"
"/L6\"Bash\" Line Comment = # Escape Char = \\ String Chars = ' File Extensions = SH CSH\n"
"/Delimiters = ~!@$%^*()+=/\\[]{}:;\"<>'´` ,	.?\n"
"/Indent Strings = \"{(\"\n"
"/Unindent Strings = \"})\"\n"
"/Function String = \"%[a-zA-Z_]*(\"\n"
"/C1\n"
"'\n"
"{\n"
"}\n"
"&&\n"
"||\n"
"$\n"
"alias\n"
"break\n"
"case continue\n"
"do done\n"
"elif else esac exit export\n"
"fi for\n"
"if in\n"
"return\n"
"set\n"
"then\n"
"unalias unset\n"
"while\n"
"/C2\n"
"halt\n"
"ifconfig init initlog insmod\n"
"linuxconf lsmod\n"
"modprobe\n"
"reboot rmmod route\n"
"shutdown\n"
"traceroute\n"
"/C3\n"
"]  \n"
"[\n"
"awk\n"
"basename\n"
"cat cp\n"
"echo egrep\n"
"fgrep\n"
"gawk grep gzip\n"
"kill killall\n"
"less\n"
"md mkdir mv\n"
"nice\n"
"pidof ps\n"
"rd read rm rmdir\n"
"sed sleep\n"
"test touch\n"
"ulimit uname usleep\n"
"zcat zless\n"
"/C4\n"
"`\n"
"-a -b -c -d -e -f -g -h -i -j -k -l -m -n -o -p -q -r -s -t -u -v -w -x -z\n"
"/C5\n"
"-eq -ge -gt -le -lt \n"
"= \n"
"!=\n"
"\n";
